#!/bin/bash

# Update the system
sudo dnf update -y

# Install required packages
sudo dnf install -y git wget curl tar java-21-openjdk java-21-openjdk-devel

# Verify Java
java -version

# Install Maven
cd /opt

sudo wget https://dlcdn.apache.org/maven/maven-3/3.9.15/binaries/apache-maven-3.9.15-bin.tar.gz

sudo tar -xzf apache-maven-3.9.15-bin.tar.gz

sudo mv apache-maven-3.9.15 maven

# Configure environment variables
cat <<EOF | sudo tee /etc/profile.d/maven.sh
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk
export M2_HOME=/opt/maven
export PATH=\$PATH:\$JAVA_HOME/bin:\$M2_HOME/bin
EOF

sudo chmod +x /etc/profile.d/maven.sh

source /etc/profile.d/maven.sh

# Verify Maven
mvn -version

# Add Jenkins repository
sudo wget -O /etc/yum.repos.d/jenkins.repo \
https://pkg.jenkins.io/redhat-stable/jenkins.repo

# Import Jenkins GPG key
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

# Install Jenkins
sudo dnf install -y jenkins

# Enable and start Jenkins
sudo systemctl enable --now jenkins

# Verify Jenkins
sudo systemctl status jenkins --no-pager

# Display Jenkins initial admin password
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
